#!/usr/bin/env node

import { readdir, readFile, writeFile, mkdir, stat } from 'node:fs/promises';
import { join } from 'node:path';
import { writeRunResultsFromJUnit, type RunResults } from '../src/runner/reporters/json-reporter.js';

type Manifest = {
  runId: string;
  createdAt: string;
  targets: Array<{ id: string; path: string }>;
};

type StoredServerInfo = {
  name?: string;
  baseUrl?: string;
  specVersion?: string;
  capabilities?: string[];
};

function layout(title: string, body: string): string {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link rel="stylesheet" href="/assets/style.css">
  <title>${title}</title>
</head>
<body>
  <header>
    <h1>${title}</h1>
    <nav><a href="/index.html">← All Runs</a></nav>
  </header>
  <main>${body}</main>
  <footer><small>Generated by will-it-blossom</small></footer>
</body>
</html>`;
}

function statusBadge(summary: any): string {
  return summary.failed > 0
    ? '<span class="badge badge-red">fail</span>'
    : '<span class="badge badge-green">pass</span>';
}

async function loadManifests(artifactsDir: string): Promise<Manifest[]> {
  try {
    const runs = await readdir(artifactsDir);
    const manifests: Manifest[] = [];

    for (const run of runs) {
      const manifestPath = join(artifactsDir, run, 'manifest.json');
      try {
        await stat(manifestPath);
        const content = await readFile(manifestPath, 'utf8');
        manifests.push(JSON.parse(content));
      } catch {
        // Skip if manifest doesn't exist
      }
    }

    return manifests.sort((a, b) => (a.runId < b.runId ? 1 : -1));
  } catch {
    return [];
  }
}

async function renderRun(
  artifactsDir: string,
  outDir: string,
  manifest: Manifest
): Promise<void> {
  const runOut = join(outDir, 'runs', manifest.runId);
  await mkdir(runOut, { recursive: true });

  let targetLinks = '';

  for (const t of manifest.targets) {
    const resultsPath = join(artifactsDir, manifest.runId, t.path);
    let res: RunResults | undefined;

    try {
      const resultsContent = await readFile(resultsPath, 'utf8');
      res = JSON.parse(resultsContent) as RunResults;
    } catch (error) {
      const errno = error as NodeJS.ErrnoException;
      if (errno?.code === 'ENOENT') {
        res = await regenerateResultsFromArtifacts(artifactsDir, manifest.runId, t.id);
      }

      if (!res) {
        console.warn(`Could not render target ${t.id}:`, error);
        continue;
      }
    }

    if (!res) {
      continue;
    }

    // Render target page
    const file = join(runOut, `${t.id}.html`);
    const caps = res.capabilities.map(c => `<code>${c}</code>`).join(' ');

    const testsRows = res.tests
      .sort((a, b) => a.title.localeCompare(b.title))
      .map(
        te => `
        <tr class="test-${te.status}">
          <td>${escapeHtml(te.title)}</td>
          <td><span class="status-${te.status}">${te.status}</span></td>
          <td>${(te.requirements || []).map(r => `<code>${r}</code>`).join(' ')}</td>
          <td>${te.durationMs}ms</td>
          <td>${te.skipReason ? escapeHtml(te.skipReason) : ''}</td>
        </tr>`
      )
      .join('');

    const body = `
      <h2>Target: ${t.id} ${statusBadge(res.summary)}</h2>
      <div class="info-grid">
        <div><strong>Base URL:</strong> ${res.baseUrl}</div>
        <div><strong>Spec:</strong> ${res.specVersion ?? '—'}</div>
        <div><strong>Capabilities:</strong> ${caps || '—'}</div>
      </div>

      <details open>
        <summary><strong>Summary</strong></summary>
        <ul class="summary-list">
          <li class="passed">Passed: ${res.summary.passed}</li>
          <li class="failed">Failed: ${res.summary.failed}</li>
          <li class="skipped">Skipped: ${res.summary.skipped}</li>
          <li>Duration: ${res.summary.durationMs} ms</li>
        </ul>
      </details>

      <h3>Tests</h3>
      <table class="table">
        <thead>
          <tr>
            <th>Test</th>
            <th>Status</th>
            <th>Requires</th>
            <th>Duration</th>
            <th>Notes</th>
          </tr>
        </thead>
        <tbody>${testsRows}</tbody>
      </table>

      <div class="artifacts">
        <h3>Artifacts</h3>
        <ul>
          <li><a href="../../../artifacts/${manifest.runId}/${t.id}/feature-matrix.md">Feature Matrix (MD)</a></li>
          <li><a href="../../../artifacts/${manifest.runId}/${t.id}/junit.xml">JUnit XML</a></li>
        </ul>
      </div>
    `;

    await writeFile(file, layout(`${manifest.runId} – ${t.id}`, body), 'utf8');
    targetLinks += `<li><a href="./${t.id}.html">${t.id}</a></li>`;
  }

  // Render run index
  const body = `
    <h2>Run ${manifest.runId}</h2>
    <p><strong>Created:</strong> ${new Date(manifest.createdAt).toLocaleString()}</p>
    <h3>Targets</h3>
    <ul class="target-list">${targetLinks}</ul>
  `;

  await writeFile(join(runOut, 'index.html'), layout(`Run ${manifest.runId}`, body), 'utf8');
}

async function regenerateResultsFromArtifacts(
  artifactsDir: string,
  runId: string,
  targetId: string
): Promise<RunResults | undefined> {
  const targetDir = join(artifactsDir, runId, targetId);
  const junitPath = join(targetDir, 'junit.xml');

  try {
    await stat(junitPath);
  } catch {
    return undefined;
  }

  const serverInfo = await readJsonFile<StoredServerInfo>(join(targetDir, 'server-info.json'));
  const capabilities = Array.isArray(serverInfo?.capabilities)
    ? (serverInfo?.capabilities as string[])
    : [];

  try {
    console.warn(`results.json missing for ${targetId} in run ${runId}, rebuilding from junit.xml`);
    return await writeRunResultsFromJUnit({
      junitPath,
      outDir: targetDir,
      meta: {
        runId,
        target: targetId,
        baseUrl: serverInfo?.baseUrl ?? 'unknown',
        specVersion: serverInfo?.specVersion,
        capabilities,
      },
    });
  } catch (error) {
    console.warn(`Failed to rebuild results for ${targetId}:`, error);
    return undefined;
  }
}

async function readJsonFile<T>(path: string): Promise<T | undefined> {
  try {
    const raw = await readFile(path, 'utf8');
    return JSON.parse(raw) as T;
  } catch {
    return undefined;
  }
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

async function buildSite(): Promise<void> {
  const artifactsDir = 'artifacts';
  const outDir = 'site';

  console.log('Building static site...');

  // Create output directories
  await mkdir(join(outDir, 'assets'), { recursive: true });

  // Write CSS
  await writeFile(
    join(outDir, 'assets', 'style.css'),
    `
    * { box-sizing: border-box; }
    body {
      font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      max-width: 1200px;
      margin: 0 auto;
      padding: 24px;
      line-height: 1.6;
      background: #f8f9fa;
      color: #212529;
    }
    header {
      border-bottom: 2px solid #dee2e6;
      padding-bottom: 16px;
      margin-bottom: 24px;
    }
    header h1 {
      font-size: 1.8rem;
      margin: 0 0 8px 0;
    }
    header nav { font-size: 0.9rem; }
    header nav a { color: #0d6efd; text-decoration: none; }
    header nav a:hover { text-decoration: underline; }

    .info-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 12px;
      margin: 16px 0;
      padding: 16px;
      background: white;
      border-radius: 8px;
      border: 1px solid #dee2e6;
    }

    .table {
      border-collapse: collapse;
      width: 100%;
      background: white;
      border-radius: 8px;
      overflow: hidden;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    .table th,
    .table td {
      border: 1px solid #dee2e6;
      padding: 12px;
      text-align: left;
    }
    .table th {
      background: #e9ecef;
      font-weight: 600;
    }
    .table tr:hover {
      background: #f8f9fa;
    }

    .badge {
      display: inline-block;
      padding: 4px 8px;
      border-radius: 4px;
      font-size: 0.85rem;
      font-weight: 600;
    }
    .badge-green {
      background: #d1e7dd;
      color: #0f5132;
    }
    .badge-red {
      background: #f8d7da;
      color: #842029;
    }

    .status-passed { color: #198754; font-weight: 600; }
    .status-failed { color: #dc3545; font-weight: 600; }
    .status-skipped { color: #6c757d; }

    code {
      background: #e9ecef;
      padding: 2px 6px;
      border-radius: 3px;
      font-size: 0.9em;
      font-family: 'Courier New', monospace;
    }

    details {
      margin: 16px 0;
      padding: 16px;
      background: white;
      border-radius: 8px;
      border: 1px solid #dee2e6;
    }
    summary {
      cursor: pointer;
      font-weight: 600;
      user-select: none;
    }

    .summary-list {
      list-style: none;
      padding: 0;
      margin: 12px 0 0 0;
    }
    .summary-list li {
      padding: 4px 0;
    }
    .summary-list .passed { color: #198754; }
    .summary-list .failed { color: #dc3545; }
    .summary-list .skipped { color: #6c757d; }

    .target-list,
    .artifacts ul {
      list-style: none;
      padding: 0;
    }
    .target-list li,
    .artifacts li {
      padding: 8px 0;
    }
    .target-list a,
    .artifacts a {
      color: #0d6efd;
      text-decoration: none;
    }
    .target-list a:hover,
    .artifacts a:hover {
      text-decoration: underline;
    }

    footer {
      margin-top: 48px;
      padding-top: 16px;
      border-top: 1px solid #dee2e6;
      text-align: center;
      color: #6c757d;
    }
  `,
    'utf8'
  );

  // Load manifests
  const manifests = await loadManifests(artifactsDir);

  // Render each run
  for (const m of manifests) {
    await renderRun(artifactsDir, outDir, m);
  }

  // Render index
  const runLinks = manifests
    .map(
      m =>
        `<li>
        <a href="./runs/${m.runId}/index.html">${m.runId}</a>
        <small style="color: #6c757d; margin-left: 8px;">
          ${new Date(m.createdAt).toLocaleString()}
        </small>
      </li>`
    )
    .join('');

  const indexBody = `
    <h2>Blossom Conformance Test Runs</h2>
    <p>Select a test run to view detailed results:</p>
    <ul class="target-list">${runLinks || '<li>No test runs found</li>'}</ul>
  `;

  await writeFile(join(outDir, 'index.html'), layout('Will It Blossom?', indexBody), 'utf8');

  console.log(`Site built successfully in ${outDir}/`);
}

buildSite().catch(err => {
  console.error('Error building site:', err);
  process.exit(1);
});
